### ISSUE TITLE
Updating to Ember 1.2 breaks template compiling

### ISSUE THREAD

**Issue by mtylty** [bartsqueezy/ember-handlebars-brunch#12]
The following exception is raised: 

```
Assertion Failed: `blockHelperMissing` was invoked without a helper name, which is most likely due to a mismatch between the version of Ember.js you're running now and the one used to precompile your templates. Please make sure the version of `ember-handlebars-compiler` you're using is up to date.
Error: Assertion Failed: `blockHelperMissing` was invoked without a helper name, which is most likely due to a mismatch between the version of Ember.js you're running now and the one used to precompile your templates. Please make sure the version of `ember-handlebars-compiler` you're using is up to date.
```

Probably an update to the template compiler is needed.

**Comment by bartsqueezy** [comment]
@mtylty, you are correct.  There are breaking changes between these versions.  I'll get on updating this as soon as possible.  Thanks for bringing it to my attention!

**Comment by mtylty** [comment]
@bartsqueezy I'm trying to update it myself. If I succeed I'll PR.

**Comment by bartsqueezy** [comment]
Sounds great!  Thanks for your help!

**Comment by mtylty** [comment]
Are tests working?

It requires handlebars (`var Handlebars = require('handlebars');`) but there is no node module included by the `package.json` file

**Comment by mtylty** [comment]
Also, I don' think `handlebars.js` is really needed, it could be included via `package.json`, am I correct?

**Comment by bartsqueezy** [comment]
Ember has been upgraded to 1.2.0 and handlebars to 1.1.2.  Tests have also been fixed courtesy of @gcollazo.  These issues should be fixed now.  Thanks for your help and input!
