### ISSUE TITLE
Update to handlebars-1.0.0?

### ISSUE THREAD

**Issue by yankeeinlondon** [bartsqueezy/ember-handlebars-brunch#9]
Will this updated to handlebars-1.0.0 soon? The latest ember builds are now using the 1.0 release of handlebars and just swapping in the handlebars.js into `/node_modules/ember-handlebars-brunch/vendor/handlebars.js` apparently doesn't do the trick. Admittedly that may have been a naive hope on my part but that didn't stop me from hoping.

**Comment by yankeeinlondon** [comment]
Ok I guess it was as easy as getting the latest ember-compiler, now it works for me. Still would be nice to get this updated on the repo. Is there a way to update this dependency with `Bower` or something similar?

**Comment by bartsqueezy** [comment]
@ksnyde, there are no plans to add bower to manage these dependencies at this time.  However, considering this repo itself is used as a dependency within brunch apps, I'm going to start tagging releases so users can dynamically manage which version of ember/handlebars (via npm) they need to successfully precompile templates within their app.  This should help alleviate current issues with dependency management.

**Comment by yankeeinlondon** [comment]
any update on this?
